# Generated by Django 3.1.6 on 2021-03-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_on_monday', models.BooleanField(default=False)),
                ('scheduled_on_tuesday', models.BooleanField(default=False)),
                ('scheduled_on_wednesday', models.BooleanField(default=False)),
                ('scheduled_on_thursday', models.BooleanField(default=False)),
                ('scheduled_on_friday', models.BooleanField(default=False)),
                ('scheduled_on_saturday', models.BooleanField(default=False)),
                ('scheduled_on_sunday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSteps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=30)),
                ('step_description', models.CharField(max_length=30)),
                ('step_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_points', models.IntegerField(default=0)),
                ('user_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('user_action_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_action_type', models.IntegerField(default=0)),
                ('user_action_performer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='royale.user')),
                ('user_action_target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='royale.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=30)),
                ('task_description', models.CharField(max_length=200)),
                ('task_repeating', models.BooleanField(default=False)),
                ('task_completion_time', models.DateTimeField()),
                ('task_steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royale.tasksteps')),
                ('task_weekly_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='royale.taskschedule')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_health', models.IntegerField(default=100)),
                ('user_energy', models.IntegerField(default=0)),
                ('user_shield', models.IntegerField(default=0)),
                ('user_class', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royale.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=30)),
                ('event_max_points', models.IntegerField(default=0)),
                ('event_is_public', models.BooleanField(default=True)),
                ('event_key', models.CharField(max_length=8)),
                ('event_participators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royale.eventparticipation')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royale.task')),
            ],
        ),
    ]
