# Generated by Django 3.1.6 on 2021-03-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('royale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_points', models.IntegerField(default=0)),
                ('user_description', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royale.client'),
        ),
        migrations.AlterField(
            model_name='useractions',
            name='user_action_performer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='royale.client'),
        ),
        migrations.AlterField(
            model_name='useractions',
            name='user_action_target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='royale.client'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
