# Generated by Django 3.1.5 on 2021-03-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0002_auto_20210315_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='royale.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_completion_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_steps',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='royale.tasksteps'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_weekly_schedule',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='royale.taskschedule'),
        ),
        migrations.AlterField(
            model_name='tasksteps',
            name='step_description',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
