# Generated by Django 3.1.5 on 2021-03-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0003_auto_20210317_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_weekly_schedule',
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='schedule_tasks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='royale.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_key',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
