# Generated by Django 3.1.5 on 2021-03-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0006_auto_20210317_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='schedule_tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='task_weekly_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='royale.taskschedule'),
        ),
    ]
