# Generated by Django 3.1.5 on 2021-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0008_auto_20210318_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
