# Generated by Django 3.1.5 on 2021-03-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0013_auto_20210323_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_max_points',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='user_class',
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('class_description', models.CharField(max_length=150)),
                ('class_health', models.IntegerField(default=100)),
                ('class_damage', models.IntegerField(default=10)),
                ('selected_class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='royale.eventparticipation')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='user_owned_classes',
            field=models.ManyToManyField(to='royale.Classes'),
        ),
    ]
