# Generated by Django 3.1.5 on 2021-03-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0014_auto_20210330_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('health', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='useractions',
            name='user_action_performer',
        ),
        migrations.RemoveField(
            model_name='useractions',
            name='user_action_target',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_complete_date',
            new_name='complete_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_is_public',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='eventparticipation',
            old_name='user_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='eventparticipation',
            old_name='user_energy',
            new_name='energy',
        ),
        migrations.RenameField(
            model_name='eventparticipation',
            old_name='user_health',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='eventparticipation',
            old_name='participation_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='eventparticipation',
            old_name='user_shield',
            new_name='shield',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_completion_time',
            new_name='completion_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='associated_event',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_repeating',
            new_name='repeating',
        ),
        migrations.RenameField(
            model_name='taskschedule',
            old_name='scheduled_on_friday',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='taskschedule',
            old_name='schedule_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='taskschedule',
            old_name='scheduled_on_monday',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='taskschedule',
            old_name='scheduled_on_saturday',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='taskschedule',
            old_name='scheduled_on_sunday',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='taskschedule',
            old_name='scheduled_on_thursday',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='taskschedule',
            old_name='scheduled_on_tuesday',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='taskschedule',
            old_name='scheduled_on_wednesday',
            new_name='wednesday',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_owned_classes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_participators',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_steps',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_weekly_schedule',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='royale.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='royale.task'),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='TaskSteps',
        ),
        migrations.DeleteModel(
            name='UserActions',
        ),
        migrations.AddField(
            model_name='useraction',
            name='performer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='royale.client'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='royale.client'),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='royale.task'),
        ),
        migrations.AddField(
            model_name='client',
            name='owned_classes',
            field=models.ManyToManyField(to='royale.Clazz'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='selected_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, null=True, to='royale.clazz'),
        ),
    ]
