# Generated by Django 3.1.5 on 2021-03-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0015_auto_20210330_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completion_time',
            new_name='due_time',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='completed_tasks',
            field=models.ManyToManyField(to='royale.Task'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='total_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraction',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='royale.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='owned_classes',
            field=models.ManyToManyField(blank=True, to='royale.Clazz'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='selected_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='royale.clazz'),
        ),
    ]
