# Generated by Django 3.1.5 on 2021-03-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0016_auto_20210330_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='royale.taskschedule'),
        ),
    ]
