# Generated by Django 3.1.5 on 2021-03-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0019_auto_20210330_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='complete_date',
            new_name='end_date',
        ),
    ]
