# Generated by Django 3.1.5 on 2021-04-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0020_auto_20210331_1618'),
        ('royale', '0016_auto_20210330_1721'),
    ]

    operations = [
    ]
