# Generated by Django 3.1.5 on 2021-04-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0021_merge_20210404_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='completed_steps',
            field=models.ManyToManyField(blank=True, to='royale.TaskStep'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, to='royale.Task'),
        ),
    ]
