# Generated by Django 3.1.5 on 2021-04-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0022_auto_20210408_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_key',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
