# Generated by Django 3.1.5 on 2021-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0023_event_event_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_key',
        ),
        migrations.AddField(
            model_name='event',
            name='random_seed',
            field=models.CharField(blank=True, default=0, max_length=6),
        ),
    ]
