# Generated by Django 3.1.5 on 2021-04-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0025_auto_20210422_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(default='Attack', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='royale.useractiontypes'),
        ),
    ]
