# Generated by Django 3.1.5 on 2021-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0026_auto_20210422_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractiontypes',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
