# Generated by Django 3.1.5 on 2021-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0027_useractiontypes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractiontypes',
            name='energy_cost',
            field=models.IntegerField(default=1),
        ),
    ]
