# Generated by Django 3.1.5 on 2021-04-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0029_auto_20210422_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='performer',
        ),
        migrations.AddField(
            model_name='useraction',
            name='performer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='royale.client'),
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='target',
        ),
        migrations.AddField(
            model_name='useraction',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='royale.client'),
        ),
    ]
