# Generated by Django 3.1.5 on 2021-04-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0032_auto_20210422_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='performer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='royale.eventparticipation'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='target',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='royale.eventparticipation'),
        ),
    ]
