# Generated by Django 3.1.5 on 2021-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0033_auto_20210422_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='shield',
            field=models.IntegerField(default=1),
        ),
    ]
