# Generated by Django 3.1.5 on 2021-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0034_auto_20210422_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='shield',
            field=models.FloatField(default=1),
        ),
    ]
