# Generated by Django 3.1.5 on 2021-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0035_auto_20210423_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='health',
            field=models.FloatField(default=100),
        ),
    ]
