# Generated by Django 3.1.5 on 2021-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0036_auto_20210423_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='damage_taken',
            field=models.FloatField(default=0),
        ),
    ]
